### ISSUE TITLE
Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: 

### ISSUE THREAD

**Issue by hayreddintuzel** [opentok/OpenTok-PHP-SDK#202]
I am using laravel 5.6 and opentok 4.0 my php version is 7.2.3 and I am trying to create session with that code:
``` apiKey = xxxxx;
$apiSecret = "xxxxx";
$opentok = new OpenTok($apiKey, $apiSecret);
$session = $opentok->createSession();
$session = $opentok->createSession(array( 'mediaMode' => MediaMode::ROUTED ));
$session = $opentok->createSession(array( 'location' => '12.34.56.78' ));
$sessionOptions = array(
'archiveMode' => ArchiveMode::ALWAYS,
'mediaMode' => MediaMode::ROUTED);
$session = $opentok->createSession($sessionOptions);
$sessionId = $session->getSessionId();
```

But ı am taking that error
Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</code><message>Invalid signature</message> (truncated...)
I validate my API secret and key with your tool.
I searched a lot of. But there are no solution for this. Please help me. I am creating a huge system and I trusted your API. But now, I am on trouble ☹

**Comment by hayreddintuzel** [comment]
After all my checks and tests I decided to create a new tokbox account. I tried the same thing and this time I did not get 403 forbidden errors. but when I tried to create a new session I got the 403 error again. same api key and secret works correctly 5 minutes ago. But now I am taking that error:

`Client error: POST https://api.opentok.com/session/create` resulted in a `403 Forbidden response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</code><message>token has expired</message> (truncated...)`

PLEASE HELP, MY ALL SYSTEMS ARE BASED ON TOKOX. I DO NOT KNOW WHAT I WILL DO. 
I must  dynamically crate new sessions.

**Comment by maikthomas** [comment]
Hi @hayreddintuzel Have you seen this answer? https://stackoverflow.com/a/46672684/5433407
A 403 response can happen when your server clock is out of sync with the OpenTok server.
This could explain how this happens intermittently and with different accounts.

Take a look and let us know! 
Thanks,
Mike

**Comment by hayreddintuzel** [comment]
Hi, I dont know how will a sync my server and tokbox clock. I am using php sdk not rest api. Have u got idea?

**Comment by maikthomas** [comment]
@hayreddintuzel that depends, where are you running the code (What operating system etc?)

this answer was given before for a time issue: https://github.com/opentok/Opentok-Python-SDK/issues/113#issuecomment-357813946

and gave this link for linux: https://superuser.com/questions/123962/how-can-i-permanently-fix-my-date-synchronize-problem-in-linux

**Comment by maikthomas** [comment]
@hayreddintuzel I would start by just manually checking the time on the computer where you are executing your code and compare it with any time server, to check it's not ahead or behind, you may notice here if it's different. Set the time using a time server, google to find out how, depending on your OS. And try the code again.

**Comment by hayreddintuzel** [comment]
@maikthomas solved! thanks a lot of. I am using laravel with homestead-vagrant. I sync my server time with `sudo ntpdate time.nist.gov`

Thanks a lot of again!

**Comment by karukkuvelraj** [comment]
I also got this same problem but am using it in core PHP.
Please help how to fix..........


Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</code><message>Issuer not found</message>< (truncated...) ' in D:\Xampp\htdocs\tekaptitude\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:120 Stack trace: #0 D:\Xampp\htdocs\tekaptitude\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 D:\Xampp\htdocs\tekaptitude\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 D:\Xampp\htdocs\tekaptitude\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 D:\Xampp\htdocs\tekaptitude\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp in D:\Xampp\htdocs\tekaptitude\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 120

**Comment by hayreddintuzel** [comment]
Are u using xamp or like that server?

**Comment by karukkuvelraj** [comment]
Ya am using XAMPP V3.2.2 only.Do you have any idea hayred?

**Comment by hayreddintuzel** [comment]
sorry I return late. My problem was solved by fixing my server time. Maybe ur server time is false. You should check it.

**Comment by marcioaffonso** [comment]
@karukkuvelraj, I see you reported 2 different error messages.

- on from April 3rd, the response says `token expired`, which in most cases can be fixed by setting the clock of your server, as suggested by @maikthomas. The token is created with an expiration time of some seconds after the server current timestamp.

- For the latest message, I see the error of `Issuer not found`, which in most cases means that the apiKey you are passing is not correct. I would double check that.

**Comment by karukkuvelraj** [comment]
Thank you @marcioaffonso  I have validated my API key using the tokbox credential validator as shown in the below link. I fixed my token expired problem still,but still i am not able to create my session.Do u have any other idea @marcioaffonso ..?

link: https://tokbox.com/tools/credential-validator/

**Comment by marcioaffonso** [comment]
@karukkuvelraj I just tested the sample defined here: https://github.com/opentok/OpenTok-PHP-SDK/tree/master/sample/HelloWorld and it's working, so I'm closing the issue with the SDK.

Can you please write to support@tokbox.com so a ticket will be generated and the TokBox support team will guide you to solve your issue? Thanks!

**Comment by karukkuvelraj** [comment]
@marcioaffonso thank you for the link . I will try the link you mentioned.Ya already i sent the mail.They also given me ticket.Still am waiting for their update.
